name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install sccache
      run: |
        cargo install sccache
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          ~/.cache/sccache
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Build
      run: cargo build --verbose
      
    - name: Where is dumpbin?
      if: runner.os == 'Windows'
      shell: cmd
      run: where dumpbin

    - name: List tesseract lib directory
      if: runner.os == 'Windows'
      shell: cmd
      run: dir "%USERPROFILE%\AppData\Roaming\tesseract-rs\tesseract\lib"

    - name: Check for TessMutableIterator symbols in tesseract.lib (Windows only)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        set "PATH=%PATH%;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.43.34808\bin\Hostx64\x64"
        dumpbin /symbols "%USERPROFILE%\AppData\Roaming\tesseract-rs\tesseract\lib\tesseract.lib" | findstr TessMutableIterator || exit 0
    
    - name: Run tests
      run: cargo test --verbose
